baskets/urls.py
from django.urls import path

from baskets.views import basket_add, basket_remove, basket_edit

app_name = 'basket'

urlpatterns = [
    path('basket_add/<uuid:product_id>/', basket_add, name='basket_add'),
    path('basket_remove/<uuid:basket_id>/', basket_remove, name='basket_remove'),
    path('basket_edit/<uuid:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

blogs/urls.py
from django.urls import path

from blogs.views import blogs, post_detail

app_name = 'blogs'

urlpatterns = [
    path('', blogs, name='index'),
    path('page/<int:page>/', blogs, name='page'),
    path('post_detail/<slug:post_slug>/', post_detail, name='post_detail'),
]

orders/urls.py
from django.urls import path

from orders.views import OrderUpdate, OrderList, OrderRead, OrderCreate, OrderDelete, order_forming_complete

app_name = 'orders'
urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<uuid:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<uuid:pk>/', OrderRead.as_view(), name='read'),
    path('delete/<uuid:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<uuid:pk>/', order_forming_complete, name='forming_complete'),
]

rubicon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blogs.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baskets/models.py
from uuid import uuid4

from django.db import models

from products.models import Product
from users.models import User


class BasketQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for item in self:
            item.product.quantity += item.quantity
            item.product.save()
        super(BasketQuerySet, self).delete(*args, **kwargs)


class Basket(models.Model):
    objects = BasketQuerySet.as_manager()

    uid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='ID')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Корзина для пользователя')
    # TODO: M2M for product
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукты в корзине')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество товаров в корзине')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления товара')

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        """ Отображение суммы товара с учетом количества в корзине """
        return int(self.quantity * self.product.price)

    def total_quantity(self):
        """ Общее количество товаров в корзине """
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.quantity for basket in baskets)

    def total_sum(self):
        """ Общая сумма корзины """
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.sum() for basket in baskets)

    def delete(self, *args, **kwargs):
        """
        При удалении товаров из корзины/при отмене заказа добавление товара в общее количество(возврат резерва на склад)
        """
        self.product.quantity += self.quantity
        self.save()
        super(Basket, self).delete(*args, **kwargs)

    # def save(self, *args, **kwargs):
    #     """
    #     При добавлении товаров в корзину/при оформлении заказов вычет из общего количества(резервация товара на складе)
    #     """
    #     if self.pk:
    #         item = self.get_item(self.pk)
    #         self.product.quantity -= self.quantity - item
    #     else:
    #         self.product.quantity -= self.quantity
    #     self.product.save()
    #     super(Basket, self).save(*args, **kwargs)
    #
    # @staticmethod
    # def get_item(uid):
    #     return Basket.objects.get(pk=uid).quantity

baskets/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from django.shortcuts import HttpResponseRedirect
from django.template.loader import render_to_string

from baskets.models import Basket
from products.models import Product


@login_required
def basket_add(request, product_id):
    if request.is_ajax():
        user_select = request.user
        product = Product.objects.get(pk=product_id)
        baskets = Basket.objects.filter(user=user_select, product=product)
        if baskets:
            basket = baskets.first()
            basket.quantity += 1
            basket.save()
        else:
            Basket.objects.create(user=user_select, product=product, quantity=1)
        return HttpResponse(status=200)
    else:
        return HttpResponseBadRequest('Invalid request')


@login_required
# TODO: added button delete all product in basket
def basket_remove(request, basket_id):
    try:
        basket = Basket.objects.get(pk=basket_id)
        basket.delete()
    except:
        return {'baskets': []}
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_edit(request, id, quantity):
    if request.is_ajax():
        basket = Basket.objects.get(pk=id)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()
        baskets = Basket.objects.filter(user=request.user)
        context = {'baskets': baskets}
        result = render_to_string('baskets/basket.html', context)
        return JsonResponse({'result': result})
    else:
        return HttpResponseBadRequest('Invalid request')

baskets/templates/baskets/basket.html
<div class="basket_list">
    {% if baskets %}
        <h4 class="mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина
            <span class="badge badge-secondary badge-pill">{{ baskets.0.total_quantity }}</span>
        </h4>
        {% for basket in baskets %}
            <div class="card mb-3" style="background-color: #ccddec">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description |truncatewords:15 }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ basket.uid }}" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-5 mt-1">{{ basket.sum }} руб.</div>
                            <div class="col-lg-3 mt-1">
                                <a id="{{ basket.uid }}" href="{% url 'baskets:basket_remove' basket.uid %}">
                                    <i class="fas fa-trash"></i></a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого к оплате:</p>
                <h4 class="float-right">{{ baskets.0.total_sum }} руб.</h4>
            </div>
        </div>
        <a class="btn btn-block btn-primary btn-lg float-right mb-3" href="{% url 'orders:create' %}">
            Оформить заказ
        </a>
    {% else %}
        <h4 class="mb-3 text-center">
            В корзине ничего нет
        </h4>
    {% endif %}
</div>