blogs/urls.py
from django.urls import path

from blogs.views import blogs, post_detail

app_name = 'blogs'

urlpatterns = [
    path('', blogs, name='index'),
    path('page/<int:page>/', blogs, name='page'),
    path('post_detail/<slug:post_slug>/', post_detail, name='post_detail'),
]

orders/urls.py
from django.urls import path

from orders.views import OrderUpdate, OrderList, OrderRead, OrderCreate, OrderDelete, order_forming_complete

app_name = 'orders'
urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<uuid:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<uuid:pk>/', OrderRead.as_view(), name='read'),
    path('delete/<uuid:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<uuid:pk>/', order_forming_complete, name='forming_complete'),
]

rubicon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blogs.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from uuid import uuid4

from django.conf import settings
from django.db import models

from products.models import Product


# TODO: полностью переделать заказы начиная от шаблона, заканчивая новым функционалом
class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCESSED = 'STP'
    PAID = 'PD'
    PROCESSED = 'PRD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'Формируется'),
        (SEND_TO_PROCESSED, 'Отправлен в обработку'),
        (PAID, 'Оплачен'),
        (PROCESSED, 'Обрабатывается'),
        (READY, 'Готов к выдачи'),
        (CANCEL, 'Отмена заказа'),
    )
    uid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='ID')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Заказчик')
    created = models.DateTimeField(auto_now=True, verbose_name='Время создания заказа')
    updated = models.DateTimeField(auto_now_add=True, verbose_name='Время обновления заказа')
    paid = models.DateTimeField(null=True, blank=True, verbose_name='Время оплаты заказа')
    status = models.CharField(choices=ORDER_STATUS_CHOICES, max_length=50, default=FORMING, verbose_name='Состояние')
    is_active = models.BooleanField(default=True, verbose_name='Выполнен ли заказ?')

    def __str__(self):
        return f'Текущий заказ {self.uid}'

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.get_product_cost(), items)))

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    # def get_items(self):
    #     pass

    def delete(self, using=None, keep_parents=False):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='ID')
    order = models.ForeignKey(Order, related_name='orderitems', on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукты в заказе')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество товара в заказе')

    def get_product_cost(self):
        return self.product.price * self.quantity

orders/forms.py
from django import forms

from orders.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemsForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(OrderItemsForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

orders/views.py
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from baskets.models import Basket
from orders.forms import OrderItemsForm
from orders.models import Order, OrderItem


class OrderList(ListView):
    template_name = 'orders/order_list.html'
    model = Order
    title = 'GeekShop | Список заказов'


class OrderCreate(CreateView):
    template_name = 'orders/orders_create.html'
    model = Order
    fields = []
    success_url = reverse_lazy('orders:list')
    title = 'GeekShop | Создание заказа'

    def get_context_data(self, **kwargs):
        context = super(OrderCreate, self).get_context_data()
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_item = Basket.objects.filter(user=self.request.user)
            if basket_item:
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=basket_item.count())
                formset = OrderFormSet()

                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_item[num].product
                    form.initial['quantity'] = basket_item[num].quantity
                    form.initial['price'] = basket_item[num].product.price
                basket_item.delete()
            else:
                formset = OrderFormSet()

        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
            if self.object.get_total_cost() == 0:
                self.object.delete()
        return super(OrderCreate, self).form_valid(form)


class OrderUpdate(UpdateView):
    template_name = 'orders/orders_update.html'
    model = Order
    fields = []
    success_url = reverse_lazy('orders:list')
    title = 'GeekShop | Создание заказа'

    def get_context_data(self, **kwargs):
        context = super(OrderUpdate, self).get_context_data()
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:

            formset = OrderFormSet(instance=self.object)
            for num, form in enumerate(formset.forms):
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
            if self.object.get_total_cost() == 0:
                self.object.delete()
        return super(OrderUpdate, self).form_valid(form)


class OrderRead(DetailView):
    template_name = 'orders/orders_read.html'
    model = Order
    title = 'GeekShop | Просмотр заказа'


class OrderDelete(DeleteView):
    template_name = 'orders/orders_delete.html'
    model = Order
    success_url = reverse_lazy('orders:list')
    title = 'GeekShop | Удаление заказа'


def order_forming_complete(request, pk):
    order = Order.objects.get(uid=pk)
    order.status = Order.SEND_TO_PROCESSED
    order.save()
    return HttpResponseRedirect(reverse('orders:list'))

# # резервация/отмена резерва через сигналы
# @receiver(pre_save, sender=OrderItem)
# @receiver(pre_save, sender=Basket)
# def product_quantity_update_save(sender, instance, **kwargs):
#     if instance.pk:
#         item = instance.get_item(int(instance.pk))
#         instance.product.quantity -= instance.quantity - item
#     else:
#         instance.product.quantity -= instance.quantity
#     instance.product.save()
#
#
# @receiver(pre_delete, sender=OrderItem)
# @receiver(pre_delete, sender=Basket)
# def product_quantity_update_delete(sender, instance, **kwargs):
#     instance.product.quantity += instance.quantity
#     instance.save()

orders/templates/orders/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title> {{ title }} </title>
    {% block css %} {% endblock %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
<body style="background: none">
<!-- Navigation top -->
{% include 'users/navbar.html' %}

<div class="container-sm mt-5">
    {% block content %} {% endblock %}
</div>


{% block footer %} {% endblock %}

<!-- Jquery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<!-- Bootstrap -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<!-- JavaScript -->
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="{% static 'js/basket.js' %}"></script>
<script src="{% static 'js/orders.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</body>
</html>

orders/templates/orders/order_list.html
{% extends 'orders/base.html' %}
{% load static %}

{% block content %}
    <div class="text-center card">
        <div class="h2 text-center head">Ваши заказы,
            {% if user.first_name %}
                {{ user.first_name|title }}
            {% else %}
                Пользователь
            {% endif %}
        </div>
        <table class="table orders_list">
            <thead>
            <tr>
                <th>ID</th>
                <th>Создан</th>
                <th>Обновлен</th>
                <th>Статус</th>
            </tr>
            </thead>
            <tbody>
            {% for item in object_list %}
                {% if item.is_active %}
                    <tr>
                        <td class="td1 orders_list">{{ item.pk }}</td>
                        <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.get_status_display }}</td>
                        <td>
                            <a id="start-purchase-link-td" href="{% url 'orders:read' item.pk %}">Посмотреть</a>
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <a id="start-purchase-link-td"
                                   href="{% url 'orders:update' item.pk %}">Редактировать</a>
                            {% endif %}
                        </td>
                        <td>
                            <a id="start-purchase-link-td" href="{% url 'orders:delete' item.pk %}">Отменить заказ</a>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>

        <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5 mr-4">
            <a id="start-purchase-link" href="{% url 'index' %}">Вернуться на главную</a>
        </button>
        <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5">
            <a id="start-purchase-link" href="{% url 'orders:create' %}"> Новый заказ </a>
        </button>
    </div>
{% endblock %}

orders/templates/orders/orders_create.html
{% extends "orders/base.html" %}
{% load static %}

{% block content %}
    {% if object %}
        <div class="h3">Заказ №{{ object.pk }} от {{ object.created|date:"Y-m-d H:i:s" }}</div>
        <p class="">
            <b>Заказчик:</b> {{ user.last_name }} {{ user.first_name }}
        </p>
        <p>
            <b>Обновлен:</b> {{ object.updated|date:"Y-m-d H:i:s" }}
        </p>
        <p>
            <b>Статус:</b> {{ object.get_status_display }}
        </p>
        <hr class="hr-shadow">
        <p>
            <b>Общее количество товаров:</b>
            <span class="order_total_quantity">{{ object.get_total_quantity }}</span>
        </p>
        <p>
            <b>Общая стоимость:</b>
            <span class="order_total_cost">{{ object.get_total_cost }}</span> руб.
        </p>
    {% endif %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}

                                {% if field.name == 'price' %}
                                    {% if not field.value %}
                                    {% else %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }} руб </span>
                                    {% endif %}
                                {% else %}
                                    {{ field }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <div class="d-flex justify-content-center">
                <button id="start-purchase-btn" type="submit" value="сохранить" class="btn btn-lg mb-1">
                    Продолжить оформление
                </button>
            </div>
            {% if user.is_staff or user.is_superuser %}
                {% if object.status == 'FM' %}
                    <div class="container">
                        <div class="d-flex justify-content-around">
                            <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5 mt-4 mr-3">
                                <a id="start-purchase-link" href="{% url 'orders:forming_complete' object.pk %}">
                                    Принять в обработку
                                </a>
                            </button>
                            <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5 mt-4 mr-3">
                                <a id="start-purchase-link" href="{% url 'orders:delete' object.pk %}">Удалить</a>
                            </button>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
            <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5 mt-4 mr-3">
                <a id="start-purchase-link" href="{% url 'orders:list' %}">К списку заказов</a>
            </button>
            <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5 mt-4">
                <a id="start-purchase-link" href="{% url 'index' %}">Вернуться на главную</a>
            </button>
        </form>
    </div>

{% endblock %}

orders/templates/orders/orders_delete.html
{% extends 'orders/base.html' %}
{% load static %}

{% block content %}

    <div class="category_delete">
        <div class="h2">Уверены, что хотите отменить заказ №{{ object.pk }}?</div>
        {% if object %}
            <p>
                <b>Заказчик:</b> {{ user.last_name }} {{ user.first_name }}
            </p>
            <div class="basket_list mb-3">
                <b>В заказе:</b>
                {% for item in object.orderitems.select_related %}
                    <div class="basket_record">
                        <img style="height: 150px" src="{{ item.product.image.url }}"
                             alt="{{ item.product.short_desc }}">
                        <span class="category_name">
                   {{ item.product.category.name }}
               </span>
                        <span class="product_name">{{ item.product.name }}, </span>
                        <span class="product_price">{{ item.product.price }}&nbspруб</span>
                        <span class="product_quantitiy">x {{ item.quantity }} шт.
               </span>
                        <span class="product_cost">= {{ item.get_product_cost }}&nbspруб
               </span>
                    </div>
                {% endfor %}
            </div>
            <p>
                <b>Общее количество товаров:</b> {{ object.get_total_quantity }}
            </p>
            <p>
                <b>Общая стоимость:</b> {{ object.get_total_cost }} руб.
            </p>
            <form action="{% url 'orders:delete' object.pk %}" method="post">
                {% csrf_token %}
                <input id="start-purchase-btn" class="btn btn-lg mb-5" type="submit" value="Отменить заказ">
                <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5 ml-3">
                    <a id="start-purchase-link" href="{% url 'orders:list' %}">Вернуться к списку заказов</a>
                </button>
            </form>
        {% endif %}
    </div>
{% endblock %}

orders/templates/orders/orders_read.html
{% extends "orders/base.html" %}
{% load static %}

{% block content %}

    {% if object %}
        <div class="h3">Заказ №{{ object.pk }} от {{ object.created|date:"Y-m-d H:i:s" }}</div>
        <p class="">
            <b>Заказчик:</b> {{ user.last_name }} {{ user.first_name }}
        </p>
        <p>
            <b>Обновлен:</b> {{ object.updated|date:"Y-m-d H:i:s" }}
        </p>
        <p>
            <b>Статус:</b> {{ object.get_status_display }}
        </p>
    {% endif %}

    <div class="basket_list mb-3">
        <b>В заказе:</b>
        {% for item in object.orderitems.select_related %}
            <div class="basket_record">
                <img style="height: 150px" src="{{ item.product.image.url }}"
                     alt="{{ item.product.short_desc }}">
                <span class="category_name">
                   {{ item.product.category.name }}
               </span>
                <span class="product_name">{{ item.product.name }}, </span>
                <span class="product_price">{{ item.product.price }}&nbspруб</span>
                <span class="product_quantitiy">x {{ item.quantity }} шт.
               </span>
                <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
            </div>
        {% endfor %}
    </div>
    <hr class="hr-shadow">
    <p>
        <b>Общее количество товаров:</b> {{ object.get_total_quantity }}
    </p>
    <p>
        <b>Общая стоимость:</b> {{ object.get_total_cost }} руб.
    </p>
    <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5 mt-4 mr-3">
        <a id="start-purchase-link" href="{% url 'orders:list' %}">К списку заказов</a>
    </button>
    <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5 mt-4">
        <a id="start-purchase-link" href="{% url 'index' %}">Вернуться на главную</a>
    </button>

{% endblock %}

orders/templates/orders/orders_update.html
{% extends "orders/base.html" %}
{% load static %}

{% block content %}
    {% if object %}
        <div class="h3">Заказ №{{ object.pk }} от {{ object.created|date:"Y-m-d H:i:s" }}</div>
        <p class="">
            <b>Заказчик:</b> {{ user.last_name }} {{ user.first_name }}
        </p>
        <p>
            <b>Обновлен:</b> {{ object.updated|date:"Y-m-d H:i:s" }}
        </p>
        <p>
            <b>Статус:</b> {{ object.get_status_display }}
        </p>
    {% endif %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}

                                {% if field.name == 'price' %}
                                    {% if not field.value %}
                                    {% else %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }} руб </span>
                                    {% endif %}
                                {% else %}
                                    {{ field }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <p>
                <b>Общее количество товаров:</b>
                <span class="order_total_quantity">{{ object.get_total_quantity }}</span>
            </p>
            <p>
                <b>Общая стоимость:</b>
                <span class="order_total_cost">{{ object.get_total_cost }}</span> руб.
            </p>
            <div class="d-flex justify-content-center">
                <button id="start-purchase-btn" type="submit" value="сохранить" class="btn btn-lg mb-1">
                    Продолжить оформление
                </button>
            </div>
            <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5 mt-4 mr-3">
                <a id="start-purchase-link" href="{% url 'orders:list' %}">К списку заказов</a>
            </button>
            <button id="start-purchase-btn" type="button" class="btn btn-lg mb-5 mt-4">
                <a id="start-purchase-link" href="{% url 'index' %}">Вернуться на главную</a>
            </button>
        </form>
    </div>

{% endblock %}