blogs/urls.py
from django.urls import path

from blogs.views import blogs, post_detail

app_name = 'blogs'

urlpatterns = [
    path('', blogs, name='index'),
    path('page/<int:page>/', blogs, name='page'),
    path('post_detail/<slug:post_slug>/', post_detail, name='post_detail'),
]

rubicon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blogs.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from uuid import uuid4

from django.db import models
from django.urls import reverse
from django.utils import timezone

from users.models import User


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    uid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='ID')
    title = models.CharField(max_length=256, verbose_name='Заголовок поста')
    image = models.ImageField(upload_to='blogs_post_images', verbose_name='Изображение поста')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор поста')
    slug = models.SlugField(max_length=250, unique_for_date='publish', unique=True,
                            db_index=True, blank=True, verbose_name='URL')
    body = models.TextField(verbose_name='Содержимое поста')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Время публикации поста')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Время создания поста')
    updated = models.DateTimeField(auto_now=True, verbose_name='Время изменения поста')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name='Статус поста')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:post_detail', args=[self.slug])


class Comment(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='ID')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', verbose_name='Пост')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Никнейм комментатора')
    body = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Комментарий создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Комментарий изменен')
    active = models.BooleanField(default=True, verbose_name='Статус комментария')

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return '{} прокомментировал {}'.format(self.user, self.post)

blogs/forms.py
from django import forms

from blogs.models import Comment


class CommentForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Comment
        fields = ('body',)

blogs/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from blogs.forms import CommentForm
from blogs.models import Post, Comment


def index(request):
    return render(request, 'blogs/index.html', context={'title': 'Рубикон'})


def blogs(request, page=1):
    posts = Post.objects.all()
    paginator = Paginator(posts, 2)
    try:
        posts_paginator = paginator.page(page)
    except PageNotAnInteger:
        posts_paginator = paginator.page(1)
    except EmptyPage:
        posts_paginator = paginator.page(paginator.num_pages)
    context = {
        'title': 'Блог',
        'posts': posts_paginator,
    }
    return render(request, 'blogs/blogs.html', context=context)


def post_detail(request, post_slug):
    post = get_object_or_404(Post, status='published', slug=post_slug)
    comments = Comment.objects.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
            return HttpResponseRedirect(request.path)
    else:
        comment_form = CommentForm()
    context = {
        'title': 'Подробнее о посте',
        'post': post,
        'user': request.user,
        'comments': comments,
        'comment_form': comment_form}
    return render(request, 'blogs/post_detail.html', context=context)

blogs/templates/blogs/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
<body>
<!-- Navigation top -->
{% include 'users/navbar.html' %}

<!-- Jquery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<!-- Bootstrap -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<!-- JavaScript -->
<script src="{% static 'js/auth-admin.js' %}"></script>
<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>

{% block content %} {% endblock %}
{% block footer %} {% endblock %}

</body>
</html>

blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            {% for post in posts %}
                <div class="col-lg-6 col-md-6 mb-6">
                    <div class="card h-100" style="background-color: #ccddec">
                        <div class="card-body">
                            <img class="rounded mb-2" src="{{ post.image.url }}" width="100%"/>
                            <h4 class="card-title">
                                <a class="my_link" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h4>
                            <p class="card-text">{{ post.body|truncatewords:25 }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-2 mb-2">
            <ul class="pagination mt-3">
                <li class="page-item {% if not posts.has_previous %} disabled {% endif %}">
                    <a class="page-link-custom" href="{% if posts.has_previous %}
                       {% url 'blogs:page' posts.previous_page_number %}
                       {% else %} # {% endif %}" tabindex="-1" aria-disabled="true">
                        Предыдущая
                    </a>
                </li>
                {% for page in posts.paginator.page_range %}
                    <li class="page-item">
                        <a class="page-link-custom" href="{% url 'blogs:page' page %}">{{ page }}</a>
                    </li>
                {% endfor %}
                <li class="page-item {% if not posts.has_next %} disabled{% endif %} ">
                    <a class="page-link-custom" href="{% if posts.has_next %}
                    {% url 'blogs:page' posts.next_page_number %}{% else %} # {% endif %}">Следующая
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">&copy; ООО «Рубикон» {% now "Y" %}</p>
        </div>
    </footer>
{% endblock %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}
{% load static %}

{% block content %}
    <section>
        <div class="container-sm">
            <div class="">
                <div class="col-lg-9 index_text">
                    <p class="mt-5">Компания «Рубикон» — IT-предприятие, основное направление деятельности которого –
                        информационная безопасность. Мы занимаемся решением задач по аудиту, созданию и оптимизации
                        IT-инфраструктур.</p>
                    <p>Если ваша организация нуждается в грамотном подходе к решению вопросов информационной
                        безопасности – свяжитесь с нами любым из представленных на сайте способов. Наши специалисты
                        дадут развёрнутую консультацию, ответят на все ваши вопросы.</p>
                    <p>Компания «Рубикон» имеет необходимые лицензии от регуляторов и сертификаты, подтверждающие работу
                        с ведущими компаниями в сфере информационной безопасности.</p>
                </div>
                <button class="btn-custom">
                    <a class="my_link" style="color: white" href="{% url 'blogs:index' %}"> Читать блог </a>
                </button>
            </div>
        </div>
    </section>
{% endblock %}

blogs/templates/blogs/post_detail.html
{% extends "blogs/base.html" %}

{% block content %}
    <div class="container-sm mt-5 mb-5">
        <div id="card" class="card" style="background-color: #ccddec">
            <div class="card-body">
                <div class="d-flex float-sm-left">
                    <img class="rounded ml-2 mr-4 mt-2" src="{{ post.image.url }}" width="100%"/>
                </div>
                <h4 class="card-title"> {{ post.title }} </h4>
                <p class="text-capitalize"> Опубликовано {{ post.publish }}</p>
                <p class="card-text"> {{ post.body|linebreaks }} </p>
            </div>
            <div class="card-body">
                <h5 class="card-title"> Комментарии <span class="text-muted">• {{ post.comments.count }}</span></h5>
                {% for comment in post.comments.all %}
                    {% if comment.active %}
                        <div class="card mt-2 mb-2">
                            <div class="card-body" style="background-color: #daeefe;">
                                <p>{{ comment.user }} <span class="text-muted"> • {{ comment.created }}</span></p>
                                {{ comment.body|linebreaks }}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                {% if not user.is_authenticated %}
                    <hr class="hr-shadow">
                    <h5 class="card-title"> Чтобы оставлять комментарий, нужно сначала авторизоваться </h5>
                {% endif %}
                {% if user.is_authenticated %}
                    <hr class="hr-shadow">
                    <h5 class="card-title"> Ваш комментарий </h5>
                    <form action="{% url 'blogs:post_detail' post.slug %}" method="post">
                        {% csrf_token %}
                        {{ comment_form.as_p }}
                        <div class="d-flex justify-content-center">
                            <button class="btn-custom" type="submit">Опубликовать комментарии</button>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark ">
        <p class="m-0 text-center text-white">&copy; ООО «Рубикон» {% now "Y" %}</p>
    </footer>
{% endblock %}