blogs/urls.py
from django.urls import path

from blogs.views import blogs, post_detail

app_name = 'blogs'

urlpatterns = [
    path('', blogs, name='index'),
    path('page/<int:page>/', blogs, name='page'),
    path('post_detail/<slug:post_slug>/', post_detail, name='post_detail'),
]

orders/urls.py
from django.urls import path

from orders.views import OrderUpdate, OrderList, OrderRead, OrderCreate, OrderDelete, order_forming_complete

app_name = 'orders'
urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<uuid:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<uuid:pk>/', OrderRead.as_view(), name='read'),
    path('delete/<uuid:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<uuid:pk>/', order_forming_complete, name='forming_complete'),
]

rubicon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blogs.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import UserLoginFormView, UserRegisterFormView, UserLogoutView, UserProfileFormView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginFormView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', UserProfileFormView.as_view(), name='profile'),
    path('registration/', UserRegisterFormView.as_view(), name='registration'),
    path('verify/<str:email>/<str:activate_key>/', UserRegisterFormView.verify, name='verify'),
]

users/models.py
from datetime import timedelta
from uuid import uuid4

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class User(AbstractUser):
    uid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='ID')
    age = models.PositiveIntegerField(default=18, verbose_name='Возраст')
    email = models.EmailField(unique=True, verbose_name='Почта')
    image = models.ImageField(upload_to='users_images', null=True, blank=True, verbose_name='Фотография')
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(auto_now=True, blank=True)

    def safe_delete_user(self):
        self.is_active = False
        self.save()

    def is_activation_key_expires(self):
        if now() <= self.activation_key_expires + timedelta(hours=48):
            return False
        return True


class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'W'
    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж'),
    )
    user = models.OneToOneField(User, unique=True, db_index=True, on_delete=models.CASCADE, primary_key=True,
                                verbose_name='Профиль пользователя')
    about = models.TextField(blank=True, null=False, verbose_name='О себе')
    gender = models.CharField(choices=GENDER_CHOICES, blank=True, max_length=2, verbose_name='Пол')
    langs = models.CharField(blank=True, max_length=100, default='RU', verbose_name='Язык')

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, created, **kwargs):
        if not created:
            instance.userprofile.save()

users/forms.py
import hashlib
import random

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User, UserProfile


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес эл. почты'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save()
        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode('utf-8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf-8')).hexdigest()
        user.save()
        return user


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    age = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email', 'age')


class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(UserProfileEditForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            if filed_name != 'gender' and filed_name != 'langs':
                field.widget.attrs['class'] = 'form-control py-4'
            elif filed_name == 'about':
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] = 'form-control'

users/views.py
from django.conf import settings
from django.contrib import messages, auth
from django.contrib.auth.views import LogoutView, LoginView
from django.core.mail import send_mail
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView, FormView

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm, UserProfileEditForm
from users.models import User


class UserRegisterFormView(FormView):
    model = User
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:login')
    title = 'GeekShop - Регистрация'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = form.save()
            if self.send_verify_link(user):
                messages.success(self.request, 'Для завершения регистрации пройдите верификацию по почте!')
                return HttpResponseRedirect(reverse('users:login'))
            else:
                messages.error(request, form.errors)
        else:
            messages.error(request, form.errors)
        context = {'form': form}
        return render(request, self.template_name, context)

    def send_verify_link(self, user):
        verify_link = reverse('users:verify', args=[user.email, user.activation_key])
        subject = f'Для активации учетной записи {user.username} пройдите по ссылки'
        # {settings.DOMAIN_NAME} убрал настройку чтобы в начале ссылки для активации не было mail.ru пока что
        message = f'Для подтверждения учетной записи {user.username} на портале \n {verify_link}'
        return send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)

    def verify(self, email, activate_key):
        user = User.objects.get(email=email)
        if user and user.activation_key == activate_key and not user.is_activation_key_expires():
            user.activation_key = ''
            user.activation_key_expires = None
            user.is_active = True
            user.save()
            auth.login(self, user, backend='django.contrib.auth.backends.ModelBackend')
        return render(self, 'users/verification.html')


class UserLoginFormView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'GeekShop - Авторизация'


class UserLogoutView(LogoutView):
    template_name = 'blogs/index.html'


class UserProfileFormView(UpdateView):
    title = 'GeekShop - Профиль'
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')
    template_name = 'users/profile.html'

    def post(self, request, *args, **kwargs):
        form = UserProfileForm(data=request.POST, files=request.FILES, instance=request.user)
        profile_form = UserProfileEditForm(data=request.POST, files=request.FILES, instance=request.user.userprofile)
        if form.is_valid() and profile_form.is_valid():
            form.save()
        return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super(UserProfileFormView, self).get_context_data()
        context['profile'] = UserProfileEditForm(instance=self.request.user.userprofile)
        return context

    def get_object(self, queryset=None):
        return User.objects.get(pk=self.request.user.pk)

    def form_valid(self, form):
        messages.success(self.request, 'Данные успешно сохранены')
        super(UserProfileFormView, self).form_valid(form)
        return HttpResponseRedirect(self.get_success_url())

    # добавлено в контекстный процессор
    # def get_context_data(self, **kwargs):
    #     context = super(UserProfileFormView, self).get_context_data()
    #     context['baskets'] = Basket.objects.filter(user=self.request.user)
    #     return context
#
# @login_required
# def profile(request):
#     user = request.user
#     if request.method == 'POST':
#         form = UserProfileForm(instance=user, files=request.FILES, data=request.POST)
#         if form.is_valid():
#             messages.success(request, 'Data has been saved ')
#             form.save()
#             return HttpResponseRedirect(reverse('users:profile'))
#         else:
#             print(form.errors)
#     else:
#         form = UserProfileForm(instance=user)
#     context = {
#         'title': 'GeekShop - Профиль',
#         'form': form,
#         'baskets': Basket.objects.filter(user=user),
#     }
#     return render(request, 'users/profile.html', context)

# def registration(request):
#     if request.method == 'POST':
#         form = UserRegistrationForm(data=request.POST)
#         if form.is_valid():
#             messages.success(request, 'Congratulation! Success registration ')
#             form.save()
#             return HttpResponseRedirect(reverse('users:login'))
#         else:
#             print(form.errors)
#     else:
#         form = UserRegistrationForm()
#     context = {'title': 'GeekShop - Регистрация', 'form': form}
#     return render(request, 'users/registration.html', context=context)

# def logout(request):
#     auth.logout(request)
#     return HttpResponseRedirect(reverse('index'))

# def login(request):
#     if request.method == 'POST':
#         form = UserLoginForm(data=request.POST)
#         if form.is_valid():
#             username = request.POST['username']
#             password = request.POST['password']
#             user = auth.authenticate(username=username, password=password)
#             if user and user.is_active:
#                 auth.login(request, user)
#                 return HttpResponseRedirect(reverse('index'))
#             else:
#                 print(form.errors)
#     else:
#         form = UserLoginForm()
#     context = {'title': 'GeekShop - Авторизация', 'form': form}
#     return render(request, 'users/login.html', context=context)

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
</head>
<body style="padding-top: 56px;">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %}  {% endblock %}
    </div>
</div>
<!-- Jquery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<!-- Bootstrap -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<!-- JavaScript -->
<script src="{% static 'js/auth-admin.js' %}"></script>
<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>

{% block js %} {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends "users/base.html" %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                {% if messages or form.errors %}
                    <div class="alert alert-dismissible fade show
                    {% if messages %} alert-success {% else %} alert-warning {% endif %}" role="alert"
                         style="margin-top: 50px;">
                        {% if messages %}
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        {% else %}
                            {{ form.non_field_errors }}
                        {% endif %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Авторизация</h3>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{% url 'users:login' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя
                                </label>
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                {{ form.password }}
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a class="small" href="#">Забыли пароль?</a>
                                <input class="btn btn-primary" type="submit" value="Авторизоваться">
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="form-row">
                            <div class="col-md-10 offset-md-1">
                                <div class="form-group">
                                    <label for="">Вход через социальные сети</label>
                                    <div class="form-group d-flex align-items-center justify-content-center mt-4 mb-0">
                                        <a href="{% url 'social:begin' 'vk-oauth2' %}?next=/">
                                            <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i></a>
                                        {#<a href="{% url 'social:begin' 'github' %}?next=/">#}
                                        {#    <i class="fab fa-github fa-2x" style="color: #303030;"></i></a>#}
                                    </div>
                                    <hr class="hr-shadow">
                                    Нужен аккаунт?
                                    <a class="btn btn-round form-control"
                                       href="{% url 'users:registration' %}">Зарегистрируйся!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/navbar.html
{% load static %}
<nav id="nav-bar-my" class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top nav-bar-my">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'vendor\img\logo\logo.png' %}" alt="logo" width="50%"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto box_block ">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:index' %}"> Блог </a>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}"> Услуги </a>
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle box_block1" href="#" id="navbarDropdown"
                               role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <ul class="dropdown-menu ba" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
                                <li><a class="dropdown-item" href="{% url 'orders:list' %}">Заказы</a></li>
                                {% if user.is_staff or user.is_superuser %}
                                    <li>
                                        <a class="dropdown-item ba" href="{% url 'admin:index' %}">Админ-панель</a>
                                    </li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider"/>
                                </li>
                                <li><a class="dropdown-item" href="{% url "users:logout" %}">Выйти</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Войти
                                <i class="fas fa-sign-in-alt"></i>
                            </a>
                        </li>
                    {% endif %}
            </ul>
        </div>
    </div>
</nav>

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
    <!-- Navigation top -->
    {% include 'users/navbar.html' %}
    <!-- main content -->
    <div class="container" style="margin-top: 3.5rem!important;">
        <div class="row">
            <div class="col-lg-7 mb-5">
                <div class="text-center">
                    <img width="450" height="450" src='{% if user.image %} {{ user.image.url }}
                {% else %}{% static 'vendor/img/users/default_avatar.jpg' %} {% endif %}' class="img-thumbnail">
                </div>
                <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}"> Имя пользователя </label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}"> Адрес электронной почты
                            </label>
                            {{ form.email }}
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}"> Имя </label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}"> Фамилия </label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file"> {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">
                                    Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-4">
                            <label class="small mb-1" for="{{ form.age.id_for_label }}"> Возраст </label> {{ form.age }}
                        </div>
                        <div class="col-lg-4">
                            <label class="small mb-1" for="{{ profile.gender.id_for_label }}"> Пол </label>
                            {{ profile.gender }}
                        </div>
                        <div class="col-lg-4">
                            <label class="small mb-1" for="{{ profile.langs.id_for_label }}"> Язык </label>
                            {{ profile.langs }}
                        </div>
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ profile.about.id_for_label }}"> О себе </label>
                            {{ profile.about }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <button class="btn btn-block btn-lg mb-lg-5 btn-primary" type="submit">Сохранить</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-5">
                {% include 'baskets/basket.html' %}
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/basket.js' %}"></script>
{% endblock %}

users/templates/users/registration.html
{% extends "users/base.html" %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                        </div>
                        <div class="card-body">
                            <form method="post" action="{% url 'users:registration' %}">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1"
                                                   for="{{ form.first_name.id_for_label }}">
                                                Имя
                                            </label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1"
                                                   for="{{ form.last_name.id_for_label }}">
                                                Фамилия
                                            </label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                            Имя пользователя
                                        </label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                            Адрес электронной почты
                                        </label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1"
                                                   for="{{ form.password1.id_for_label }}">
                                                Пароль
                                            </label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">
                                                Подтверждение пароля
                                            </label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row justify-content-center">
                                    <div class="form-group ">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:login' %}">
                                    Уже есть аккаунт? Авторизоваться
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/verification.html
{% extends "users/base.html" %}

<div class="col-lg-5">
    <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">Активация профиля</h3>
        </div>
        <div class="card-body text-center">
            {% if user.is_authenticated %}
                <h3>Поздравляем!</h3>
                <br>
                <h4>Пользователь <em>{{ user.username }}</em> подтвержден.</h4>
            {% else %}
                <h3>Верификация не пройдена.</h3>
            {% endif %}
            <br>
            <button class="btn btn-round form-control">
                <a href="{% url 'index' %}" style="text-decoration-line: none">На главную</a>
            </button>
        </div>
    </div>
</div>